export enum Subjects {
  AccountCreated = 'account:created',
  GenerateOTP = 'generate:OTP',
  GenerateReset = 'generate:Reset',
  UserDeleted = 'user:deleted',
  UserCreated = 'user:created',
  UserUpdated = 'user:updated',
  ProductCreated = 'product:created',
  ProductUpdated = 'product:updated',
  ProductDeleted = 'product:deleted',
  CustomProductCreated = 'customProduct:created',
  CustomProductUpdated = 'customProduct:updated',
  CustomProductDeleted = 'customProduct:deleted',
  OfferCreated = 'offer:created',
  OfferUpdated = 'offer:updated',
  OfferDeleted = 'offer:deleted',
  OrderCreated = 'order:created',
  OrderPaymentUpdated = 'orderPayment:updated',
  OrderStatusUpdated = 'orderStatus:updated',
  OrderDeleted = 'order:deleted',
  PaymentSuccess = 'payment:success',
  PaymentFailed = 'payment:failed',
  BuildWebsite = 'build:website',
}
