export enum Subjects {
  AccountCreated = 'account:created',
  GenerateOTP = 'generate:OTP',
  GenerateReset = 'generate:Reset',
  UserDeleted = 'user:deleted',
  UserCreated = 'user:created',
  UserUpdated = 'user:updated',
  ProductDeleted = 'product:deleted',
  OfferDeleted = 'offer:deleted',
  CustomProductDeleted = 'custom product:deleted',
  ProductCreated = 'product:created',
  OfferCreated = 'offer:created',
  CustomProductCreated = 'custom product:created',
  ProductUpdated = 'product:updated',
  OfferUpdated = 'offer:updated',
  CustomProductUpdated = 'custom product:updated',
  OrderCreated = 'order:created',
  OrderDeleted = 'order:deleted',
  OrderPaymentUpdated = 'orderPayment:updated',
  OrderStatusUpdated = 'orderStatus:updated',
}
