apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: server
build:
  artifacts:
    - image: tsriramaraju/auth
      context: auth
    - image: tsriramaraju/users
      context: users
    - image: tsriramaraju/products
      context: products
deploy:
  kubectl:
    manifests:
      - k8s/auth-depl.yaml
      - k8s/users-depl.yaml
      - k8s/products-depl.yaml
      - k8s/ingress-srv.yaml
      - k8s/nats-depl.yaml
